Add lifecycle management for repository collaborators
krateoplatformops/github-provider pull request #2
Opened 2024-08-21 12:07 UTC by banh-gao

This PR enables the github-provider to manage the lifecycle of repository collaborators by using a new CR.

In particular it can:
- Add collaborators to a repository
- Update permissions for an existing collaborator (reconciliation)

2024-09-19 07:45 UTC, banh-gao commented
This PR now also includes the repository permissions management also for teams

2024-09-19 08:19 UTC, matteogastaldello requested changes

2024-09-19 08:19 UTC, matteogastaldello commented on apis/collaborator/v1alpha1/managed.go
> +func (mg *Collaborator) GetDeletionPolicy() prv1.DeletionPolicy {
`provider-runtime` has been upgraded to version 0.9.0, where `deletionPolicy` has been removed. Before merging, you need to rebase the project with the main branch.

Additionally, you need to follow the folder and file structure as shown in [this commit](https://github.com/krateoplatformops/github-provider/tree/e34223ea86cefb28a991738c7f7091bf800bbb74/apis/repo/v1alpha1).

2024-09-19 08:19 UTC, matteogastaldello commented on apis/collaborator/v1alpha1/repo_types.go
Filename should be called "collaborator_types.go"

2024-09-19 08:19 UTC, matteogastaldello commented on apis/teamRepo/v1alpha1/repo_types.go
Filename should be called "teamrepo_types.go"

2024-09-19 08:19 UTC, matteogastaldello commented on Makefile
The Makefile has been removed in favor of the [scripts folder](https://github.com/krateoplatformops/github-provider/tree/e34223ea86cefb28a991738c7f7091bf800bbb74/scripts).

2024-09-25 09:17 UTC, banh-gao commented on apis/collaborator/v1alpha1/managed.go
> +func (mg *Collaborator) GetDeletionPolicy() prv1.DeletionPolicy {
Code rebased

2024-09-25 09:17 UTC, banh-gao commented on apis/collaborator/v1alpha1/repo_types.go
file renamed

2024-09-25 09:17 UTC, banh-gao commented on apis/teamRepo/v1alpha1/repo_types.go
file renamed

2024-09-25 09:19 UTC, banh-gao commented on Makefile
The makefile is still present on main branch.
However I tested the changes using scripts in the folder and made changed to test new resources with them.

2024-10-08 12:28 UTC, banh-gao commented
@matteogastaldello can you please review this PR?
Our customer is waiting for it.

2024-10-08 12:35 UTC, banh-gao commented on scripts/reboot.sh
this change was made because the test secret can be created only AFTER the namespace for it is created.

2024-10-08 13:07 UTC, matteogastaldello requested changes
Can you please remove the Makefile? We have decided to remove it in favor of the scripts folder.

2024-10-08 13:07 UTC, matteogastaldello commented on Makefile
Can you please remove the Makefile? We have decided to remove it in favor of the scripts folder.

2024-10-08 15:48 UTC, banh-gao commented on Makefile
it's in the main branch. BTW I removed it from mine.

2024-10-08 15:53 UTC, matteogastaldello approved these changes

2024-10-08 15:54 UTC, merged